TASK-28: Create README.md front-end
Atacha/Atacha-website pull request #5
Opened 2021-05-15 22:20 UTC by AcJoell

# Description:

## Introduction
Create the frontend readme.md file with the following information:
   - Getting Started (how to start with the project)
   - Technology Stack (The components with which it was created)
   - Contribution (Link to the contributing file)
   - Team (name and function of team people)

#

## Conclusion

- Described the prerequisites to start the repo
- Described how you should do the installation of the dependencies
- I described the executions that I can do within the project (both back-end and front-end to date)

- I described how we had formed our technological stack, both in front, back, design and marketing (but it is empty)

- I put two contribution files (CONTRIBUTING.md and CODE-OF CONDUCT) for you to review and rate, they are based on the Mozilla Code of Conduct Application Scale, it seemed like a good idea to me

- Described the team that started the project

- The license space is still empty, due to my ignorance of it

- And a section of Acknowledgments that is empty

2021-05-15 22:28 UTC, CesarJOritzM commented on CODE-OF-CONDUCT.md
> +ser informado poniéndose en contacto con el equipo del proyecto en <billie@billiecodes.com>.
the email must be the one from atacha

2021-05-15 22:32 UTC, CesarJOritzM commented on CODE-OF-CONDUCT.md
> +Covenant] (https://www.contributor-covenant.org), versión 1.4, disponible
You must direct to the atacha page

2021-05-15 22:33 UTC, CesarJOritzM commented on CONTRIBUTING.md
> +en [translations](https://www.contributor-covenant.org/translations).
You must direct to the Atacha page

2021-05-15 22:41 UTC, CesarJOritzM requested changes
I consider that it should only carry the information regarding the front-end, since the detail of the back-end will be done in the README.md of it

2021-05-15 22:42 UTC, CesarJOritzM commented on README.md
> +_Back-end_
only front-end information

2021-05-15 22:47 UTC, CesarJOritzM requested changes
I consider that it should only carry the information regarding the front-end, since the detail of the back-end will be done in the README.md of it

2021-05-15 22:47 UTC, CesarJOritzM commented on README.md
> +**1.** Modo desarrollo dentro del Back-end
Only front-end information

2021-05-15 22:47 UTC, CesarJOritzM commented on CODE-OF-CONDUCT.md
> +ser informado poniéndose en contacto con el equipo del proyecto en <billie@billiecodes.com>.
the email must be the one from atacha

2021-05-15 22:47 UTC, CesarJOritzM commented on CODE-OF-CONDUCT.md
> +Covenant] (https://www.contributor-covenant.org), versión 1.4, disponible
You must direct to the atacha page

2021-05-15 22:47 UTC, CesarJOritzM commented on CONTRIBUTING.md
> +[FAQ](https://www.contributor-covenant.org/faq). Hay traducciones disponibles
You must direct to the Atacha page

2021-05-15 22:47 UTC, CesarJOritzM commented on README.md
> +_Back-end_
only front-end information

2021-05-15 22:47 UTC, CesarJOritzM requested changes
I consider that it should only carry the information regarding the front-end, since the detail of the back-end will be done in the README.md of it

2021-05-15 22:58 UTC, ruloCode commented on README.md
> +* etc.
¿Podrías quitar este etc ?

2021-05-15 23:04 UTC, ruloCode requested changes
Los documentos están utilizando inglés y español en desorden. 


![image](https://user-images.githubusercontent.com/48034545/118380458-73afd080-b5a7-11eb-84f1-d371c17f0ada.png)


Si estás considerando agregar el español sería mejor tener la versión original en inglés y una alterna solo en **español.**
![image](https://user-images.githubusercontent.com/48034545/118380506-d99c5800-b5a7-11eb-9170-06b8ab611468.png)

2021-05-16 16:42 UTC, CesarJOritzM requested changes
Change name point 2

2021-05-16 16:42 UTC, CesarJOritzM commented on README.md
> +**2.** Run production mode on the Front-end
Run build in front-end

2021-05-18 00:14 UTC, CesarJOritzM approved these changes

2021-05-20 01:03 UTC, ruloCode approved these changes
LGTM (Look go to me)

2021-05-20 01:03 UTC, ruloCode commented on CONTRIBUTING.md
> +[FAQ](https://www.contributor-covenant.org/faq). Hay traducciones disponibles
La guía de contribución  me debe ser de utilidad en:
- Cómo crear un Pull request
- Cómo nombrar una rama 
- Cómo nombrar un commit
- El proceso de un PR hasta producción

2021-05-20 01:03 UTC, ruloCode commented on CONTRIBUTING.md
> +[FAQ](https://www.contributor-covenant.org/faq). Hay traducciones disponibles
este recurso podría ser de ayuda
https://github.com/Sphinx-Society/kaizen-web-client/blob/master/CONTRIBUTING.md

2021-05-20 23:42 UTC, merged